title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/My Org62 pic.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/bhumika-sharma-a8734ab0/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working as an Engineering Manager at Salesforce.
  I have total IT experience of above 20 Years.
  <br>
  </p>



theme: jekyll-theme-minimal
